# Generated by Django 5.2.8 on 2026-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='school_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='', max_length=20),
        ),
    ]
