# Generated by Django 5.2.8 on 2026-06-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business_school_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('po_box', models.CharField(blank=True, max_length=100)),
                ('uneb_pri_no', models.CharField(blank=True, max_length=100)),
                ('uneb_olevel_center_no', models.CharField(blank=True, max_length=100)),
                ('uneb_alevel_center_no', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logos/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='school/stamps/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_settings', to='api.business')),
            ],
        ),
    ]
