# Generated by Django 5.2.8 on 2026-06-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_upload_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='done', max_length=20),
        ),
    ]
