# Generated by Django 5.2.8 on 2026-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_mark_term_to_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['year', 'term', 'subject', 'assessment']},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='mark',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'assessment', 'term', 'year')},
        ),
    ]
