# Generated by Django 5.2.8 on 2026-06-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_add_school_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('assigned_pages', models.JSONField(blank=True, default=list)),
                ('additional_role', models.CharField(blank=True, choices=[('class_teacher', 'Class Teacher'), ('deputy_head', 'Deputy Head Teacher'), ('head_teacher', 'Head Teacher'), ('dos', 'Director of Studies'), ('bursar', 'Bursar'), ('librarian', 'Librarian'), ('sports', 'Sports Master/Mistress'), ('none', 'None')], default='none', max_length=50)),
                ('sign', models.ImageField(blank=True, null=True, upload_to='staff/signs/')),
                ('email_prefix', models.CharField(blank=True, max_length=100)),
                ('otp', models.CharField(blank=True, max_length=8)),
                ('otp_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='api.business')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
